services:
  - type: web
    name: network-cell-analyzer
    runtime: python
    rootDir: NetworkCellAnalyzer/server
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    plan: free
